update_fastlane
default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :test do
      scan(scheme: "FlowCommon", clean: true, skip_slack: !is_ci, slack_only_on_failure: true, xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO")
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
